### ISSUE TITLE
Rename every package to org.mitk.cbica.captk.*

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk2.0#10]
Rename every package to org.mitk.cbica.captk.*

**Comment by ashishsingh18** [comment]
rename to org.cbica.captk.*

**Comment by dboun** [comment]
> rename to org.cbica.captk.*

we can't, it has to start with org.mitk

**Comment by ashishsingh18** [comment]
Here are some links:
https://sourceforge.net/p/mitk/mailman/message/36642411/
https://phabricator.mitk.org/T24149#122378

We may need to try it and check.

**Comment by dboun** [comment]
> We may need to try it and check.

Try what? The solution they provide is basically modifying the superbuild, which is something we want to avoid. See:

> It is quite strict indeed but for now you have two options: change the rules in your copy of MITK, or go with org.mitk.kcl… until we made these rules less strict (I’ll create a task for this for 2018.04.4 which has no schedule yet).

(we can't modify GetMyTargetLibraries anywhere, because we don't have an actual top-level CMakeLists.txt, MITK picks up things automatically)

**Comment by dboun** [comment]
@ashishsingh18

PHIEstimator should be:
Module: CaPTkPHIEstimatorModule
Plugin: org.mitk.cbica.captk.phiestimator (notice the lowercase)

_In the module_, filenames should be CaPTk**CLASSNAME**.h/cpp and the class should be captk::**CLASSNAME**

**Comment by dboun** [comment]
fixed
