### ISSUE TITLE
[PHIEstimator] Plugin: Instruction box at the top

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk2.0#143]
There is no instructions at the top of the plugin. i.e. A short description, like the other algorithms have.

It is a QGroupBox with a QLabel in it. The text for the instructions for the other algorithms are set in the ui file, not in code, so put it there to keep it consistent. To make it easier, look at the one of the other algorithms to see how to do it, copy the bullet points character etc

**Comment by ashishsingh18** [comment]
@dboun I am aware of this. Adding instructions is pretty simple. However, it creates a lot of clutter and the UI seems so busy. I prefer to have the instructions available via the 'help' menu.

**Comment by dboun** [comment]
I don't think it looks cluttered but as you wish
