### ISSUE TITLE
Remove jsoncpp and replace with qt json module

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk2.0#23]
CaptkCohortJSonFromFileSystem.h
CaptkCohortJSonFromFileSystem.cpp
CaptkWriteJsonToFile.h
CaptkWriteJsonToFile.cpp
etc.

Parts of these need to be rewritten using qt json module.

And remove jsoncpp files from captkcommon.

**Comment by dboun** [comment]
done
