### ISSUE TITLE
incorrect license on installer

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk2.0#52]
The installer shows MITK license. 

![image](https://user-images.githubusercontent.com/43445206/73490940-8afb8800-437b-11ea-9716-1dc0f35f59fa.png)

**Comment by dboun** [comment]
About this, I find the instances below on MITK's repo where cpack and license are mentioned in the same line. Could be helpful on figuring out what we need to override:

```bash
dimitris@pc:~/Work/MITK-Nightly/MITK-src$ grep -nriF license | grep -i cpack
Applications/PluginGenerator/SetupPackaging.cmake:43:set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
Applications/PluginGenerator/SetupPackaging.cmake:44:set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
Applications/PluginGenerator/ProjectTemplate/CMake/CPackSetup.cmake:5:set(CPACK_PACKAGE_DESCRIPTION_FILE "${PROJECT_SOURCE_DIR}/LICENSE")
Applications/PluginGenerator/ProjectTemplate/CMake/CPackSetup.cmake:6:set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")
CMake/mitkSetupCPack.cmake:92:set(CPACK_PACKAGE_DESCRIPTION_FILE "${MITK_SOURCE_DIR}/LICENSE")
CMake/mitkSetupCPack.cmake:93:set(CPACK_RESOURCE_FILE_LICENSE "${MITK_SOURCE_DIR}/LICENSE")
CMake/NSIS.template.in:569:  !insertmacro MUI_PAGE_LICENSE "@CPACK_RESOURCE_FILE_LICENSE@"
```

**Comment by dboun** [comment]
Maybe these two are the most important

```bash
CMake/mitkSetupCPack.cmake:92:set(CPACK_PACKAGE_DESCRIPTION_FILE "${MITK_SOURCE_DIR}/LICENSE")
CMake/mitkSetupCPack.cmake:93:set(CPACK_RESOURCE_FILE_LICENSE "${MITK_SOURCE_DIR}/LICENSE")
```

**Comment by dboun** [comment]
> When you look into MITK's top-level CMakeLists.txt in the Installation section around line 1240 you can see that the default CPack variables are set in mitkSetupCPack.cmake and that they can be overridden by CPackOptions.cmake files like you already did. In mitkSetupCPack you find the variables CPACK_PACKAGE_DESCRIPTION_FILE and CPACK_RESOURCE_FILE_LICENSE that both set the MITK license.

(Also, I don't mean to brag - but I predicted both in the comment above) (that was def a brag)

**Comment by dboun** [comment]
@ashishsingh18 close this if it worked
