### ISSUE TITLE
no desktop shortcut with package installation on windows

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk2.0#57]
no desktop shortcut with package installation on windows

**Comment by dboun** [comment]
- Is this about incise or captk?
- Whichever it was did you turn off the other app in cmake?
- Did you click "create desktop shortcut" in the installer?

**Comment by ashishsingh18** [comment]
My bad..shortcut checkbox wasn't checked. It works when shortcut is enabled. And the the icon also shows up. This is for captk.
