### ISSUE TITLE
PHI Estimator segmentation mask should be 2 label and 3D only

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk2.0#72]
PHI Estimator segmentation mask should be 2 label and 3D only

-Add checks for 2 label mask 
-Add check for 3D

**Comment by dboun** [comment]
If you want to check for dimensionality and only display 3D you can. Dimension is property and properties can be turned into bool predicates.

But alternatively you can display all segmentations and show a red message when the user selects non-3D.

**Comment by dboun** [comment]
(not an enhancement either :P)

**Comment by ashishsingh18** [comment]
opening another issue for labels and closing this one as part of it is done.
