### ISSUE TITLE
Add some context menu functions in the datamanager to showcase how it's done

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk2.0#95]
Maybe Susan Denoising or Split segmentation labels

This will be in the same menu that stuff like 'Convert to Segmentation' is

**Comment by ashishsingh18** [comment]
It would be better to put it separately and not in the context menu. Perhaps create a pre-processing menu? Or add another tab along side their image processing tools.

For showcasing you can add an example for this just like you did earlier.

**Comment by dboun** [comment]
Ok then. I think it's better to add an example, I just wanted to showcase the usage somehow

**Comment by dboun** [comment]
This was done in "common" plugin (although it might have to go). Anyway, closing this
